// 完整版菜单比较多，将 rank 抽离出来，在此方便维护

const home = 0, // 平台规定只有 home 路由的 rank 才能为 0 ，所以后端在返回 rank 的时候需要从非 0 开始
  vueflow = 29,
  dataUpload = 1,
  productStageManual = 2,
  adAnalysis = 3,
  finishedLinkMonitor = 4,
  trialLinkMonitor = 5,
  potentialLinkMonitor = 6,
  naturalStageMonitor = 7,
  table = 8,
  form = 9,
  list = 10,
  result = 11,
  error = 12,
  frame = 13,
  nested = 14,
  permission = 15,
  system = 16,
  monitor = 17,
  tabs = 18,
  about = 19,
  codemirror = 20,
  markdown = 21,
  editor = 22,
  flowchart = 23,
  formdesign = 24,
  board = 25,
  ppt = 26,
  mind = 27,
  guide = 28,
  menuoverflow = 29,
  chatai = 30,
  ganttastic = 31,
  components = 32,
  able = 33,
  customCategory = 34,
  offlineProducts = 35,
  competitor = 36;

export {
  home,
  dataUpload,
  chatai,
  vueflow,
  ganttastic,
  components,
  able,
  table,
  form,
  list,
  result,
  error,
  frame,
  nested,
  permission,
  system,
  monitor,
  tabs,
  about,
  codemirror,
  markdown,
  editor,
  flowchart,
  formdesign,
  board,
  ppt,
  mind,
  guide,
  menuoverflow,
  productStageManual,
  adAnalysis,
  finishedLinkMonitor,
  trialLinkMonitor,
  potentialLinkMonitor,
  naturalStageMonitor,
  customCategory,
  offlineProducts,
  competitor
};
